name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          check-latest: true

      - name: Build
        run: go build -o FTPDumper .

      - name: Auto Increment Semver Action
        uses: MCKanpolat/auto-semver-action@v1
        id: versioning
        with:
          releaseType: patch
          incrementPerCommit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Next Release Number
        run: echo ${{ steps.versioning.outputs.version }}

      - name: Upload binary file
        uses: softprops/action-gh-release@v2

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: MatrixTM/FTPDumper

        with:
          files: FTPDumper
          tag_name: beta-${{ steps.versioning.outputs.version }}
          prerelease: true
          name: Beta ${{ steps.versioning.outputs.version }}
          repository: MatrixTM/FTPDumper
          body: |
            ## Beta ${{ steps.versioning.outputs.version }} 💭
            
            ${{ github.event.head_commit.message }}

            [Download 📥](https://github.com/MatrixTM/FTPDumper/releases/download/beta-${{ steps.versioning.outputs.version }}/FTPDumper)


permissions:
  contents: write
  packages: write